BEGIN TRANSACTION;
IF OBJECT_ID('Origen', 'U') IS NOT NULL
    DROP TABLE ORIGEN;

CREATE TABLE ORIGEN (
    IdOrigen INT PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(30) NOT NULL
);
COMMIT TRANSACTION;
