BEGIN TRANSACTION;
IF OBJECT_ID('SUBCATEGORIAS', 'U') IS NOT NULL
    DROP TABLE SUBCATEGORIAS;

CREATE TABLE SUBCATEGORIAS (
    IdSubcategoria INT PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(30) NOT NULL,
    Color VARCHAR(6),
    Letra VARCHAR(5)
);
COMMIT TRANSACTION;
