BEGIN TRANSACTION;
IF OBJECT_ID('CATEGORIAS', 'U') IS NOT NULL
    DROP TABLE CATEGORIAS;

CREATE TABLE CATEGORIAS (
    IdCategoria INT PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(30) NOT NULL,
    Color VARCHAR(6),
    Letra VARCHAR(5)
);
COMMIT TRANSACTION;
