BEGIN TRANSACTION;
IF OBJECT_ID('PRODUCTOS', 'U') IS NOT NULL
    DROP TABLE PRODUCTOS;

CREATE TABLE PRODUCTOS (
    IdProducto INT PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(100) NOT NULL,
    Cantidad NUMERIC(6,0),
    Medida VARCHAR(30),
    IdOrigen INT FOREIGN KEY REFERENCES ORIGEN(IdOrigen),
    Precio NUMERIC(8,2),
    Limite NUMERIC(6,2)
);
COMMIT TRANSACTION;
