BEGIN TRANSACTION;
IF OBJECT_ID('INVENTARIO', 'U') IS NOT NULL
    DROP TABLE INVENTARIO;

CREATE TABLE INVENTARIO (
    IdInventario INT PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(100) NOT NULL,
    Precio NUMERIC(8,2),
    IdProducto1 INT FOREIGN KEY REFERENCES PRODUCTOS(IdProducto),
	CantidadProducto1 NUMERIC(7,3), 
	IdProducto2 INT FOREIGN KEY REFERENCES PRODUCTOS(IdProducto),
	CantidadProducto2 NUMERIC(7,3), 
	IdProducto3 INT FOREIGN KEY REFERENCES PRODUCTOS(IdProducto),
	CantidadProducto3 NUMERIC(7,3), 
	IdProducto4 INT FOREIGN KEY REFERENCES PRODUCTOS(IdProducto),
	CantidadProducto4 NUMERIC(7,3), 
	IdProducto5 INT FOREIGN KEY REFERENCES PRODUCTOS(IdProducto),
	CantidadProducto5 NUMERIC(7,3), 
	IdProducto6 INT FOREIGN KEY REFERENCES PRODUCTOS(IdProducto),
	CantidadProducto6 NUMERIC(7,3), 
	IdProducto7 INT FOREIGN KEY REFERENCES PRODUCTOS(IdProducto),
	CantidadProducto7 NUMERIC(7,3), 
	IdProducto8 INT FOREIGN KEY REFERENCES PRODUCTOS(IdProducto),
	CantidadProducto8 NUMERIC(7,3), 
	IdProducto9 INT FOREIGN KEY REFERENCES PRODUCTOS(IdProducto),
	CantidadProducto9 NUMERIC(7,3), 
	IdProducto10 INT FOREIGN KEY REFERENCES PRODUCTOS(IdProducto),
	CantidadProducto10 NUMERIC(7,3), 
    IdCategoria INT FOREIGN KEY REFERENCES CATEGORIAS(IdCategoria),
    CostoTotal NUMERIC(8,2),
    Comanda BIT,
    IdSubCategoria INT FOREIGN KEY REFERENCES SUBCATEGORIAS(IdSubcategoria)
);
COMMIT TRANSACTION;

