BEGIN TRANSACTION;
IF OBJECT_ID('USUARIOS', 'U') IS NOT NULL
    DROP TABLE USUARIOS;

CREATE TABLE USUARIOS (
    IdUsuario INT PRIMARY KEY IDENTITY(1,1),
    Usuario VARCHAR(30) NOT NULL,
    Contraseña VARCHAR(30) NOT NULL,
    TipoUsuario VARCHAR(15),
    Ventas NUMERIC(8,2),
    Mesas INT
);
COMMIT TRANSACTION;
