BEGIN TRANSACTION;
IF OBJECT_ID('MESAS', 'U') IS NOT NULL
    DROP TABLE MESAS;

CREATE TABLE MESAS (
    IdMesa INT PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(30) NOT NULL,
    IdMesero INT FOREIGN KEY REFERENCES USUARIOS(IdUsuario),
	CantidadPersonas INT,
    Impresion BIT,
	Estatus VARCHAR(15)
);
COMMIT TRANSACTION;

